### ISSUE TITLE
App Distribution could not generate credentials from the refresh token specified.

### ISSUE THREAD

**Issue by Robotex** [fastlane/fastlane-plugin-firebase_app_distribution#178]
### Issue Description

Tried to setup firebase on a new development machine, I followed the login procedure using the plugin action firebase_app_distribution_login, pasted the login token and launched the build. On firebase_app_distribution step it throws 
> App Distribution could not generate credentials from the refresh token specified.

**Using the login token generated from firebase-cli it works correctly.**
* I noticed the plugin asks different permissions than firebase-cli (the latter asks additional permissions to show and manage firebase projects, whereas the plugin asks only to access google cloud platform services), maybe this is the problem?

##### Configuration

googleservice_info_plist_path

##### Environment

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.167.0 |
| fastlane-plugin-firebase_app_distribution | 0.2.4 |

**Comment by lfkellogg** [comment]
Hi @Robotex - thanks for the report.

Just to make sure, can you confirm that you set your `FIREBASE_TOKEN` environment variable to the exact string that was printed out in your terminal after pasting in the code from your browser?

This value from when you ran `firebase_app_distribution_login`:
```
$ bundle exec firebase run firebase_app_distribution_login
...
[13:05:15]: Set the refresh token as the FIREBASE_TOKEN environment variable
[13:05:15]: Refresh Token: <THIS VALUE>
[13:05:15]: Result: true
...
```

Should be equal to this value when running `echo $FIREBASE_TOKEN`:
```
$ echo $FIREBASE_TOKEN
<THIS VALUE>
```

**Comment by Robotex** [comment]
Hi Ifkellog,
You are right, I checked again and the value was incorrectly copied and pasted. My mistake!

Issue closed.

**Comment by uguraktas** [comment]
> Hi @Robotex - thanks for the report.
> 
> Just to make sure, can you confirm that you set your `FIREBASE_TOKEN` environment variable to the exact string that was printed out in your terminal after pasting in the code from your browser?
> 
> This value from when you ran `firebase_app_distribution_login`:
> 
> ```
> $ bundle exec firebase run firebase_app_distribution_login
> ...
> [13:05:15]: Set the refresh token as the FIREBASE_TOKEN environment variable
> [13:05:15]: Refresh Token: <THIS VALUE>
> [13:05:15]: Result: true
> ...
> ```
> 
> Should be equal to this value when running `echo $FIREBASE_TOKEN`:
> 
> ```
> $ echo $FIREBASE_TOKEN
> <THIS VALUE>
> ```

Hi I have same issue I'm sure I have a token 
when I try this 
```
$ echo $FIREBASE_TOKEN
<THIS VALUE>
```

I can see my token 
but I getting this error 
`App Distribution could not generate credentials from the refresh token specified.`

**Comment by lfkellogg** [comment]
Hi @uguraktas. A few questions to help us figure out what's going on:

1. When was the token generated?
2. What method did you use to generate the token: the firebase_app_distribution_login action, or the Firebase CLI?
3. Does the Google account you logged in with still exist?

If you don't know when or how the token was created, could you try fetching a new one using `firebase_app_distribution_login`? See [instructions here](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane#google-acc-fastlane).

**Comment by milanvadhel-mi** [comment]
Hi I have implemented workflow to distribute the build on firebase via fastlane. When i try to run the fastlane command to upload the build on firebase then it will upload it successfully, but when i try same thing with github action on github server then it will throw error like this **App Distribution could not generate credentials from the refresh token specified.**. I have tried to update the token couple of time but it will show me same thing every time. 

![Screenshot from 2022-01-03 11-36-46](https://user-images.githubusercontent.com/73939866/147903305-bd51d185-0838-4d50-baed-8c9264a2d793.png)

**Comment by izackp** [comment]
I'm currently having the same issue. I tried a token from both `bundle exec fastlane run firebase_app_distribution_login` and firebase cli. I set the FIREBASE_TOKEN to the result. I also tried setting the `firebase_cli_token` parameter inside of the fast file.

- The token was generated today. 
- It was working 2 weeks ago on a fairly recent token (2 months?). 
- The google account still exists. 
- OSX 12.1 (arm64; m1 pro)

I noticed I had trouble updating the plugin until I updated the system os to 12.1 from 11.?

**Comment by tagboola** [comment]
@izackp and @milanvadhel-mi  can you run with `debug` parameter set to `true` and paste the output, making sure to remove any sensitive information?

**Comment by milanvadhel-mi** [comment]
> @izackp and @milanvadhel-mi can you run with `debug` parameter set to `true` and paste the output, making sure to remove any sensitive information?

@tagboola Thanks for your replay. The issue is fixed now and it was happening because i was accessing github secrets directly with **secrets.key** instead of ${{secrets.key}}.

**Comment by milanvadhel-mi** [comment]
> > @izackp and @milanvadhel-mi can you run with `debug` parameter set to `true` and paste the output, making sure to remove any sensitive information?
> 
> @tagboola Thanks for your replay. The issue is fixed now and it was happening because i was accessing github secrets directly with **secrets.key** instead of **${{secrets.key}}**.

**Comment by izackp** [comment]
> can you run with `debug` parameter set to `true` and paste the output

How do I do this? I can't find any info on turning debugging on.

**Comment by kaibolay** [comment]
> > can you run with `debug` parameter set to `true` and paste the output
> 
> How do I do this? I can't find any info on turning debugging on.

Maybe use `--verbose`? See [troubleshooting documentation](http://docs.fastlane.tools/plugins/plugins-troubleshooting/#use-the-verbose-mode)

**Comment by tagboola** [comment]
Unfortunately, the `--verbose` flag won't help with debugging an issue with the app distribution plugin. Instead, set the `debug` parameter in the `firebase_app_distribution` block to `true`.

Link to the documentation:
https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane#distribute

<img width="892" alt="Screen Shot 2022-01-07 at 9 12 09 AM" src="https://user-images.githubusercontent.com/401051/148556156-62e19210-ce08-4c0a-881c-bb5adcddc9ad.png">

**Comment by izackp** [comment]
Hmm the same issue appears when uploading to apple.. so there is probably something wrong with my system as the problem is also affecting other tasks.

**Comment by glennposadas** [comment]
Still happening, fastlane 2.199.0, firebase cli 8.13.1.

**Comment by izackp** [comment]
So apparently the latest python (?; or whatever version I have) stopped using the Mac osx keychain for ssl certs. 

I ended up fixing this issue by installing certifi
```
sudo python -m pip install certifi

CERT_PATH=$(python -m certifi)
export SSL_CERT_FILE=${CERT_PATH}
export REQUESTS_CA_BUNDLE=${CERT_PATH}
```

**Comment by lfkellogg** [comment]
To summarize the previous reports on this issue, this error typically indicates an invalid refresh token, or general issues making network requests.

If you run into this error, use the following steps to debug the issue:

1. Update the plugin, and fastlane, to the latest versions
2. Run again with firebase_app_distribution's `debug` parameter set to `true` ([docs](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane#distribute)), and check the error details for more info
3. Confirm that the `FIREBASE_TOKEN` environment variable and/or `firebase_cli_token` parameter is set correctly
4. Try again with a new refresh token generated using `fastlane run firebase_app_distribution_login`

At that point if there still appears to a bug, please file a new issue. Thanks!
